[project]
name = "sample"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.5.0",
    "db2-shared-utils",
    "mcp>=1.8.1",
    "sqlalchemy>=2.0.40",
]

[tool.uv.sources]
db2-shared-utils = { path = "../shared", editable = true }

