name: Publish Python Packages

on:
  workflow_dispatch:

jobs:
  detect-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Manually define uv packages
        id: set
        working-directory: .
        run: |
          PACKAGES=$(find examples/mcp -name pyproject.toml -exec dirname {} \; | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  build:
    needs: [detect-packages]
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-packages.outputs.packages) }}
    name: Build ${{ matrix.package }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ matrix.package }}/.python-version

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: uv sync --frozen --all-extras --dev

      - name: Run pyright
        working-directory: ${{ matrix.package }}
        run: uv run --frozen pyright

      - name: Build package
        working-directory: ${{ matrix.package }}
        run: uv build

      - name: Extract safe package name
        id: extract
        run: echo "safe_name=$(basename '${{ matrix.package }}')" >> $GITHUB_OUTPUT

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ steps.extract.outputs.safe_name }}
          path: ${{ matrix.package }}/dist/

  publish:
    needs: [build, detect-packages]
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-packages.outputs.packages) }}
    name: Publish ${{ matrix.package }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ steps.extract.outputs.safe_name }}
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
